import Link from "next/link";
import { Card, EvidenceLink, MetricCard, StatusBadge, Table } from "@aicp/ui";
import { getOverview } from "./lib/data";
type RunRow = { id: string; project?: string; task?: string; status: string; stage?: string; costUsd?: number };
type Attention = { id: string; title?: string; reason?: string };
export default async function OverviewPage() {
  const overview = await getOverview(); const recentRuns = overview.recentRuns as RunRow[]; const attention = overview.attention as Attention[];
  return <div className="content"><div className="page-heading"><div><div className="eyebrow">AICP Overview</div><h1>Release readiness</h1><p className="muted">A truth-first view of governed engineering work, evidence and human attention.</p></div><div className="actions"><Link className="button button-primary" href="/runs/new">Start governed run</Link><Link className="button button-secondary" href="/demo">Open demo</Link></div></div><div className="card notice" id="release-readiness"><strong><StatusBadge status={overview.release.blocked ? "blocked" : "success"} /> <span style={{ marginLeft: 8 }}>{overview.release.overall.replaceAll("_", " ")}</span></strong><span className="muted">The Console reflects the release contract; it does not promote blocked controls.</span><ul>{attention.map((item) => <li key={item.id}>{item.title ?? item.reason ?? item.id}</li>)}</ul></div><div className="grid metrics" style={{ marginTop: 16 }}><MetricCard label="PASS controls" value={overview.release.pass} detail="from release/v1-contract.json" status="success" /><MetricCard label="BLOCKED controls" value={overview.release.blocked} detail="human attention required" status="blocked" /><MetricCard label="FAILED controls" value={overview.release.failed} detail="no failed controls observed" status={overview.release.failed ? "failed" : "success"} /><MetricCard label="Active runs" value={overview.activeRuns} detail="workflow or human review" status="running" /></div><div className="grid two-col" style={{ marginTop: 16 }}><Card title="Recent runs"><Table caption="Recent governed runs"><thead><tr><th>Status</th><th>Project / task</th><th>Stage</th><th>Cost</th><th>Open</th></tr></thead><tbody>{recentRuns.map((run) => <tr key={run.id}><td><StatusBadge status={run.status === "BLOCKED" ? "blocked" : run.status === "HUMAN_REVIEW" ? "human-required" : run.status === "COMPLETED" ? "success" : "running"} /></td><td><strong>{run.project ?? "unknown"}</strong><br /><span className="muted">{run.task ?? "task metadata unavailable"}</span></td><td>{(run.stage ?? "unknown").replaceAll("-", " ")}</td><td>${(run.costUsd ?? 0).toFixed(2)}</td><td><EvidenceLink href={`/runs/${run.id}`}>View run</EvidenceLink></td></tr>)}</tbody></Table></Card><Card title="Requires attention"><div className="stack">{attention.map((item) => <div className="split" key={item.id}><div><strong>{item.title ?? item.id}</strong><div className="muted">{item.reason ?? "Evidence is required before certification."}</div></div><StatusBadge status="blocked" /></div>)}</div></Card></div><div className="grid three-col" style={{ marginTop: 16 }}><MetricCard label="Budget today" value="—" detail={overview.budget.note} /><MetricCard label="Workflow quality" value="—" detail={overview.quality.observed} /><MetricCard label="Context efficiency" value="—" detail={overview.context.observed} /></div></div>;
}
