import Link from "next/link";
import { Card, EvidenceLink, MetricCard, StatusBadge, Table } from "@aicp/ui";
import { getTranslations } from "next-intl/server";
import { getOverview } from "./lib/data";
type RunRow = { id: string; project?: string; task?: string; status: string; stage?: string; costUsd?: number };
type Attention = { id: string; title?: string; reason?: string };
export default async function OverviewPage() {
  const [overview, t] = await Promise.all([getOverview(), getTranslations("Overview")]); const recentRuns = overview.recentRuns as RunRow[]; const attention = overview.attention as Attention[];
  return <div className="content"><div className="page-heading"><div><div className="eyebrow">{t("eyebrow")}</div><h1>{t("title")}</h1><p className="muted">{t("description")}</p></div><div className="actions"><Link className="button button-primary" href="/runs/new">{t("startRun")}</Link><Link className="button button-secondary" href="/admin">{t("adminSurfaces")}</Link><Link className="button button-secondary" href="/demo">{t("openDemo")}</Link></div></div><div className="card notice" id="release-readiness"><strong><StatusBadge status={overview.release.blocked ? "blocked" : "success"} /> <span style={{ marginLeft: 8 }}>{overview.release.overall.replaceAll("_", " ")}</span></strong><span className="muted">{t("releaseContract")}</span><ul>{attention.map((item) => <li key={item.id}>{item.title ?? item.reason ?? item.id}</li>)}</ul></div><div className="grid metrics" style={{ marginTop: 16 }}><MetricCard label={t("passControls")} value={overview.release.pass} detail={t("releaseSource")} status="success" /><MetricCard label={t("blockedControls")} value={overview.release.blocked} detail={t("humanAttention")} status="blocked" /><MetricCard label={t("failedControls")} value={overview.release.failed} detail={t("noFailedControls")} status={overview.release.failed ? "failed" : "success"} /><MetricCard label={t("activeRuns")} value={overview.activeRuns} detail={t("workflowOrReview")} status="running" /></div><div className="grid two-col" style={{ marginTop: 16 }}><Card title={t("recentRuns")}><Table caption={t("recentRuns")}><thead><tr><th>{t("status")}</th><th>{t("projectTask")}</th><th>{t("stage")}</th><th>{t("cost")}</th><th>{t("open")}</th></tr></thead><tbody>{recentRuns.map((run) => <tr key={run.id}><td><StatusBadge status={run.status === "BLOCKED" ? "blocked" : run.status === "HUMAN_REVIEW" ? "human-required" : run.status === "COMPLETED" ? "success" : "running"} /></td><td><strong>{run.project ?? t("unknown")}</strong><br /><span className="muted">{run.task ?? t("taskUnavailable")}</span></td><td>{(run.stage ?? t("unknown")).replaceAll("-", " ")}</td><td>${(run.costUsd ?? 0).toFixed(2)}</td><td><EvidenceLink href={`/runs/${run.id}`}>{t("viewRun")}</EvidenceLink></td></tr>)}</tbody></Table></Card><Card title={t("requiresAttention")}><div className="stack">{attention.map((item) => <div className="split" key={item.id}><div><strong>{item.title ?? item.id}</strong><div className="muted">{item.reason ?? t("evidenceRequired")}</div></div><StatusBadge status="blocked" /></div>)}</div></Card></div><div className="grid three-col" style={{ marginTop: 16 }}><MetricCard label={t("budgetToday")} value="—" detail={overview.budget.note} /><MetricCard label={t("workflowQuality")} value="—" detail={overview.quality.observed} /><MetricCard label={t("contextEfficiency")} value="—" detail={overview.context.observed} /></div></div>;
}
