import { test, expect } from "@playwright/test";
test.beforeEach(async ({ page }) => { await page.context().addCookies([{ name: "aicp-locale", value: "en", url: "http://127.0.0.1:3000" }]); });
test("locale defaults to Brazilian Portuguese and can switch to English", async ({ page }) => { const localeCookie = async () => (await page.context().cookies()).find((cookie) => cookie.name === "aicp-locale")?.value; await page.context().clearCookies(); await page.goto("/"); await expect(page.locator("html")).toHaveAttribute("lang", "pt-BR"); await expect(page.getByText("Interface da Console disponível")).toBeVisible(); const portugueseLocale = page.getByRole("combobox", { name: "Idioma" }); await expect(portugueseLocale).toHaveAttribute("data-hydrated", "true"); await expect(portugueseLocale.locator("option")).toHaveCount(2); await expect(portugueseLocale).toHaveValue("pt-BR"); await portugueseLocale.selectOption("en"); await expect.poll(localeCookie).toBe("en"); await expect(page.locator("html")).toHaveAttribute("lang", "en"); await expect(page.getByText("Console ready")).toBeVisible(); const englishLocale = page.getByRole("combobox", { name: "Language" }); await expect(englishLocale).toHaveAttribute("data-hydrated", "true"); await englishLocale.selectOption("pt-BR"); await expect.poll(localeCookie).toBe("pt-BR"); await expect(page.locator("html")).toHaveAttribute("lang", "pt-BR"); await expect(page.getByText("Interface da Console disponível")).toBeVisible(); });
test("overview exposes release truth and a run drill-down", async ({ page }) => { await page.goto("/"); await expect(page.getByRole("heading", { name: "Release readiness" })).toBeVisible(); await expect(page.getByText("NOT YET V1 CERTIFIED")).toBeVisible(); await page.getByRole("link", { name: "View run" }).first().click(); await expect(page.getByRole("heading", { name: "Implement idempotent retry" })).toBeVisible(); });
test("keyboard navigation reaches demo and academy", async ({ page }) => { await page.goto("/demo"); await expect(page.getByRole("heading", { name: /without provider keys/ })).toBeVisible(); await page.keyboard.press("Tab"); await page.keyboard.press("Tab"); await expect(page.locator("body")).toContainText("Demo lifecycle"); });
test("runs filters survive a shareable URL and do not hide blocked truth", async ({ page }) => { await page.goto("/runs?status=BLOCKED"); await expect(page.getByRole("combobox", { name: "Filter by status" })).toHaveValue("BLOCKED"); await expect(page.locator('td [data-status="blocked"]').first()).toBeVisible(); await expect(page.getByRole("link", { name: "Clear filters" })).toBeVisible(); });
test("command palette searches routes and Academy checkpoint requires the correct answer", async ({ page }) => { await page.goto("/"); await page.getByRole("button", { name: "⌘K Search" }).click(); const dialog = page.getByRole("dialog", { name: "Command and search palette" }); await expect(dialog).toBeVisible(); await dialog.getByRole("textbox", { name: "Search commands" }).fill("academy"); await expect(dialog.locator('a[href="/learn"]')).toBeVisible(); await page.keyboard.press("Escape"); await page.goto("/learn/foundations"); await page.getByLabel("AICP Console").check(); await page.getByRole("button", { name: "Complete checkpoint" }).click(); await expect(page.getByText("Not quite")).toBeVisible(); await page.getByLabel("Harness").check(); await page.getByRole("button", { name: "Complete checkpoint" }).click(); await expect(page.getByText("Checkpoint completed")).toBeVisible(); });
test("admin center links to same-host component UIs", async ({ page }) => { await page.goto("/admin"); await expect(page.getByRole("heading", { name: "Administrative surfaces" })).toBeVisible(); await expect(page.getByRole("link", { name: "LiteLLM Admin UI" })).toHaveAttribute("href", "/litellm"); await expect(page.getByRole("link", { name: "Neo4j Browser" })).toHaveAttribute("href", "/browser"); await expect(page.getByRole("link", { name: "pgAdmin" })).toHaveAttribute("href", "/pgadmin"); await expect(page.getByRole("link", { name: "RedisInsight" })).toHaveAttribute("href", "/redisinsight"); });
test("admin proxy routes respond on the Console hostname", async ({ page }) => { for (const route of ["/litellm", "/browser", "/pgadmin", "/redisinsight"]) { const response = await page.goto(route); await expect(response?.status(), route).toBeLessThan(400); await expect(page.url()).toContain(route); } });
